CREATE TABLE `fast_consumer_loan_order_commodity_table` (
  `unique_id` varchar(50) NOT NULL COMMENT 'id',
  `commodity_id` varchar(50) NOT NULL COMMENT '商品id',
  `commodity_name` varchar(50) NOT NULL,
  `order_id` varchar(50) NOT NULL COMMENT '订单id',
  `price` decimal(50,2) NOT NULL COMMENT '价格',
  `number` int(10) NOT NULL COMMENT '数量',
  `user_internal_code` varchar(50) NOT NULL COMMENT '用户内码',
  `seller_internal_code` varchar(50) NOT NULL COMMENT '商户内码',
  `total_amount` decimal(50,2) NOT NULL COMMENT '总金额',
  `information_state` varchar(10) NOT NULL COMMENT '信息状态',
  `pay_method` varchar(50) DEFAULT NULL COMMENT '支付方式',
  `pay_name` varchar(50) DEFAULT NULL COMMENT '支付名',
  `pay_code` varchar(50) DEFAULT NULL COMMENT '支付编码',
  `external_pay_number` varchar(50) DEFAULT NULL COMMENT '外部支付号',
  `pay_time` timestamp NULL DEFAULT NULL COMMENT '支付时间',
  `order_time` timestamp NULL DEFAULT NULL COMMENT '下单时间',
  `send_time` timestamp NULL DEFAULT NULL COMMENT '发货时间',
  `pay_message` varchar(255) DEFAULT NULL COMMENT '支付信息',
  `receipt_time` timestamp NULL DEFAULT NULL COMMENT '收货时间',
  `finish_time` timestamp NULL DEFAULT NULL COMMENT '完成时间',
  `discount_price` decimal(50,2) DEFAULT NULL COMMENT '折扣价',
  `anonymous` tinyint(10) DEFAULT NULL COMMENT '是否匿名',
  `create_time` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `mod_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;