DROP TABLE if EXISTS account_limit_table;
CREATE TABLE `account_limit_table` (


  loanAcctNo VARCHAR(13) NOT NULL COMMENT '中银消费金融账号',
  mobileNo VARCHAR(11) NOT NULL COMMENT '客戶手机号',
  acctStus VARCHAR(2) NOT NULL COMMENT '账户状态',
  creLineStus VARCHAR(2) NOT NULL COMMENT '额度状态',
  acctBalance DECIMAL(8,2) NOT NULL COMMENT '贷款余额',
  returnBalance DECIMAL(8,2) NOT NULL COMMENT '退货溢出款',
  baseTotCreLine DECIMAL(8,2) NOT NULL COMMENT '基础额度总额',
  baseUsedCreLine DECIMAL(8,2) NOT NULL COMMENT '基础额度已动用额度',
  baseRestCreLine DECIMAL(8,2) NOT NULL COMMENT '基础额度剩余可使用额度',
  tempTotCreLine DECIMAL(8,2) NOT NULL COMMENT '临时额度',
  tempUsedCreLine DECIMAL(8,2) NOT NULL COMMENT '临时额度已动用额度',
  tempRestCreLine DECIMAL(8,2) NOT NULL COMMENT '临时额度剩余可使用额度',
  dayPayTotalAmt DECIMAL(8,2) NOT NULL COMMENT '当日累计消费总金额',
  dayReturnTotalAmt DECIMAL(8,2) NOT NULL COMMENT '当日累计还款总金额',
  txnPrint DECIMAL(8,2) NOT NULL COMMENT '償還的本金',
  txnFee DECIMAL(8,2) NOT NULL COMMENT '償還的费用',
  txnOvdFee DECIMAL(8,2) NOT NULL COMMENT '償還的滞纳费',
  txnInt DECIMAL(8,2) NOT NULL COMMENT '償還的利息',
  tempFrozenAmt DECIMAL(8,2) NOT NULL COMMENT '临时冻结额度',
  creLineExpDate DATE NOT NULL COMMENT '基础额度有效期限',
  totalLoanAmt DECIMAL(8,2) NOT NULL COMMENT '實際欠款合计',
  intTot DECIMAL(8,2) NOT NULL COMMENT '利息合计',
  expenseTot DECIMAL(8,2) NOT NULL COMMENT '費用合計',
  ovdFeeTot DECIMAL(8,2) NOT NULL COMMENT '滞纳费合计',
  ovdFeeAbl DECIMAL(8,2) NOT NULL COMMENT '可免除之滞纳费',
  returnAmt DECIMAL(8,2) NOT NULL COMMENT '本期应还款额',
  nextPayDate DATE NOT NULL COMMENT  '最后还款日',
  overdueStatus VARCHAR(1) NOT NULL COMMENT '逾期状态',
  ovdDayCnt VARCHAR(3) NOT NULL COMMENT '逾期天数',
  minReturnAmount DECIMAL(8,2) NOT NULL COMMENT '解除逾期状态所需偿还金额',
  debitCardNo	VARCHAR(20) NOT NULL COMMENT '借记卡卡号',
  openBankId VARCHAR(4)	NOT NULL COMMENT  '借记卡开户銀行代號',
  decardOpenBank	VARCHAR(50) NOT NULL COMMENT '借记卡开户銀行名称',
  prov VARCHAR(20)	NOT NULL COMMENT '借记卡开户行省份',
  city VARCHAR(40) NOT NULL COMMENT 	'借记卡开户行城市',
  decardCardIssuer VARCHAR(10) NOT NULL COMMENT 	'借记卡发卡行编号',
  decardCardIssuerName VARCHAR(100) NOT NULL COMMENT 	'借记卡发卡行名称',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `mod_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='账户额度信息表';